apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.16.3
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    logging:
      loggers:
        - name: plugins.screenshotting
          level: debug
        - name: plugins.reporting
          level: debug
        - name: metrics.ops
          level: debug
    #   - name: elasticsearch.query
    #     level: debug
    xpack:
      reporting:
        roles.enabled: false
        capture.maxAttempts: 1
      reporting.encryptionKey: testfoo123testfoo123testfoo123testfoo123testfoo123
      security.encryptionKey: testfoo123testfoo123testfoo123testfoo123testfoo123
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1600"
        resources:
          limits:
            memory: 2G
            cpu: 2
