apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.1.3
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    xpack:
      reporting:
        encryptionKey: sohotcuzimcoveredinice2cool4k8s
        roles.enabled: false
        capture.maxAttempts: 1
      security.encryptionKey: sohotcuzimcoveredinice2cool4k8s
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=800"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 2
