apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.1.3
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    logging:
      loggers:
        - name: plugins.screenshotting
          level: debug
        - name: plugins.reporting
          level: debug
        - name: metrics.ops
          level: debug
    #   - name: elasticsearch.query
    #     level: debug
    xpack:
      reporting:
        roles.enabled: false
        capture.maxAttempts: 1
        encryptionKey: 2cool4k8sitssohotcuzimcoveredinice
      security.encryptionKey: 2cool4k8sitssohotcuzimcoveredinice
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=800"
        resources:
          limits:
            memory: 2.5Gi
            cpu: 2
